let text = prompt("Melumati daxil edin")
console.log(text.length)
console.log(text.includes("e"))
console.log(text.startsWith("code"))
console.log(text.endsWith("code"))
console.log(text.replaceAll("t", "####"))
